# sonar-project.properties

sonar.organization=jayakrishnasai
sonar.projectKey=SSP_MERN_Project
sonar.projectName=SSP_MERN_Project
sonar.projectVersion=1.0

# Focus scan on frontend and backend source code
sonar.sources=frontend,backend

# Target SonarCloud
sonar.host.url=https://sonarcloud.io

# Encoding of the source code
sonar.sourceEncoding=UTF-8

# Exclusions to improve scan speed and accuracy
sonar.exclusions=**/node_modules/**, **/*.spec.js, **/*.test.js, **/build/**, **/dist/**

# Javascript specific properties
sonar.javascript.environments=browser,node
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
