# sonar-project.properties

# Unique project key provided by the user
sonar.projectKey=49dea63c6a1076a5060635bc8d76cf0b611e658f

# Display name for the project
sonar.projectName=SSP_MERN_Project

# Project Version
sonar.projectVersion=1.0

# Relative paths to the source directories
# Including both frontend and backend for full visibility
sonar.sources=frontend/src,backend

# Encoding of the source code
sonar.sourceEncoding=UTF-8

# Exclusions
sonar.exclusions=**/node_modules/**, **/*.spec.js, **/*.test.js, build/**, dist/**

# Javascript specific properties
sonar.javascript.environments=browser,node
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
